
name: Test on Nogil

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: jimkring/action-python-nogil@main
      with:
        requirements-file: requirements.txt
        command: python -V
